### PR TITLE
FEAT: Adding pricing history for instrument

### PR DESCRIPTION
**Pull request by dowling-john**
adding get pricing history for instrument("Company")
adding candlestick object

### CODE REVIEW

**Comment by dowling-john** [comment]
I have just noticed a mistake in the ticker that i used for testing, I will fix it and push

**Comment by HellAmbro** [comment]
Hi, great work, i Will review and merge asap. 
Can you please provide some working example and add a sample in readme or examples folder. This will help new users to understand and use this new feature of the API. Thanks.

**Comment by dowling-john** [comment]
Hi I have added some examples and documentation.

One question about the html files that you are pushing to github pages, are these generated by a package ? 

I can update them manually but am just wondering if they are genreated by soemthing ?

**Comment by HellAmbro** [comment]
Thanks. I Will review It and merge asap.
Dont worry about GitHub Pages that is automatically generated on push.

**Pull request merged**
